SELECT NAME FROM v$database; 
SELECT USERNAME FROM DBA_USERS;

select table_name from all_tables where owner ='SYSTEM'

SELECT DISTINCT (c.constraint_type) FROM ALL_CONS_COLUMNS A JOIN ALL_CONSTRAINTS C  
ON A.CONSTRAINT_NAME = C.CONSTRAINT_NAME WHERE 
  A.OWNER='B'